#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# Reverse Marketplace — Full API Test Suite
# ═══════════════════════════════════════════════════════════════════
# Runs all API test scripts in dependency order.
#
# Usage:
#   ./run-all.sh              # Run all test suites
#   ./run-all.sh 06-posts.sh  # Run only the posts suite
#   ./run-all.sh --clean      # Run all + clean up test data after
#
# Requires: curl, jq, server at :3000, Docker (postgres)
# ═══════════════════════════════════════════════════════════════════

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_config.sh"

# ── Banner ────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   Reverse Marketplace — API Test Suite            ║${NC}"
echo -e "${BOLD}║   $(date '+%Y-%m-%d %H:%M:%S')                             ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════════════════╝${NC}"

# ── Prerequisites ─────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Checking prerequisites...${NC}"

PREREQ_FAIL=0

if ! command -v curl >/dev/null 2>&1; then
  echo -e "  ${RED}✗${NC} curl not found"
  PREREQ_FAIL=1
else
  echo -e "  ${GREEN}✓${NC} curl"
fi

if ! command -v jq >/dev/null 2>&1; then
  echo -e "  ${RED}✗${NC} jq not found — install with: brew install jq"
  PREREQ_FAIL=1
else
  echo -e "  ${GREEN}✓${NC} jq"
fi

HEALTH_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$BASE_URL/health" 2>/dev/null)
if [ "$HEALTH_CODE" != "200" ]; then
  echo -e "  ${RED}✗${NC} Server not running at $BASE_URL (got HTTP $HEALTH_CODE)"
  echo -e "    ${DIM}Start with: cd backend && npm run dev${NC}"
  PREREQ_FAIL=1
else
  echo -e "  ${GREEN}✓${NC} Server running at $BASE_URL"
fi

if ! docker exec "$PG_CONTAINER" pg_isready -U "$PG_USER" >/dev/null 2>&1; then
  echo -e "  ${YELLOW}!${NC} Docker PostgreSQL ($PG_CONTAINER) not reachable — DB-level operations will be skipped"
else
  echo -e "  ${GREEN}✓${NC} Docker PostgreSQL ($PG_CONTAINER)"
fi

if [ "$PREREQ_FAIL" -eq 1 ]; then
  echo ""
  echo -e "${RED}Prerequisites not met. Aborting.${NC}"
  exit 1
fi

# ── Initialize State ──────────────────────────────────────────────

echo ""
> "$SCRIPT_DIR/_state.sh"
echo "# Generated by run-all.sh at $(date '+%Y-%m-%d %H:%M:%S')" > "$SCRIPT_DIR/_state.sh"
echo "TIMESTAMP=\"$TIMESTAMP\"" >> "$SCRIPT_DIR/_state.sh"

# ── Parse Arguments ───────────────────────────────────────────────

SINGLE_SUITE=""
CLEANUP=false

for arg in "$@"; do
  case "$arg" in
    --clean) CLEANUP=true ;;
    *.sh) SINGLE_SUITE="$arg" ;;
  esac
done

# ── Define Suites ─────────────────────────────────────────────────

SUITES=(
  "01-health.sh"
  "02-auth.sh"
  "03-categories.sh"
  "04-users.sh"
  "05-sellers.sh"
  "06-posts.sh"
  "07-offers.sh"
  "08-transactions.sh"
  "09-messages.sh"
  "10-payments.sh"
  "11-reviews.sh"
  "12-notifications.sh"
  "13-admin.sh"
  "14-search.sh"
  "15-uploads.sh"
  "16-disputes.sh"
  "17-payouts.sh"
  "18-saved-searches.sh"
)

# ── Run Suites ────────────────────────────────────────────────────

TOTAL_PASS=0
TOTAL_FAIL=0
TOTAL_SKIP=0
SUITE_RESULTS=()
FAILED_SUITES=()

run_suite() {
  local suite="$1"
  local suite_path="$SCRIPT_DIR/$suite"

  if [ ! -f "$suite_path" ]; then
    echo -e "${RED}Suite not found: $suite${NC}"
    return 1
  fi

  echo ""
  echo -e "${BOLD}${CYAN}══════════════════════════════════════════${NC}"
  echo -e "${BOLD}${CYAN}  Running: $suite${NC}"
  echo -e "${BOLD}${CYAN}══════════════════════════════════════════${NC}"

  # Run suite, capture exit code
  bash "$suite_path"
  local exit_code=$?

  # Read the counters from the suite (they print in summary)
  # We parse the summary line from stdout
  return $exit_code
}

if [ -n "$SINGLE_SUITE" ]; then
  # Run single suite
  run_suite "$SINGLE_SUITE"
  exit $?
fi

# Run all suites in order
for suite in "${SUITES[@]}"; do
  # Reset counters for aggregation (suites track their own)
  run_suite "$suite"
  local_exit=$?

  if [ $local_exit -ne 0 ]; then
    FAILED_SUITES+=("$suite")
    SUITE_RESULTS+=("${RED}✗ $suite${NC}")
  else
    SUITE_RESULTS+=("${GREEN}✓ $suite${NC}")
  fi
done

# ── Cleanup ───────────────────────────────────────────────────────

if [ "$CLEANUP" = true ]; then
  echo ""
  echo -e "${BOLD}${YELLOW}━━━ Cleanup ━━━${NC}"

  # Reload state to get IDs
  source "$SCRIPT_DIR/_state.sh" 2>/dev/null

  if docker exec "$PG_CONTAINER" pg_isready -U "$PG_USER" >/dev/null 2>&1; then
    # Delete test-created data (in reverse dependency order)
    if [ -n "${TEST_REVIEW_ID:-}" ] && [ "$TEST_REVIEW_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM reviews WHERE id = '$TEST_REVIEW_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test review${NC}"
    fi
    if [ -n "${TEST_TRANSACTION_ID:-}" ] && [ "$TEST_TRANSACTION_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM transactions WHERE id = '$TEST_TRANSACTION_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test transaction${NC}"
    fi
    if [ -n "${TEST_CONVERSATION_ID:-}" ] && [ "$TEST_CONVERSATION_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM messages WHERE conversation_id = '$TEST_CONVERSATION_ID';" 2>/dev/null
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM conversations WHERE id = '$TEST_CONVERSATION_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test conversation${NC}"
    fi
    if [ -n "${TEST_OFFER_ID:-}" ] && [ "$TEST_OFFER_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM offers WHERE id = '$TEST_OFFER_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test offer${NC}"
    fi
    if [ -n "${TEST_POST_ID:-}" ] && [ "$TEST_POST_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM posts WHERE id = '$TEST_POST_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test post${NC}"
    fi
    if [ -n "${NEW_USER_ID:-}" ] && [ "$NEW_USER_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM users WHERE id = '$NEW_USER_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test user${NC}"
    fi
    if [ -n "${VERIFICATION_REQUEST_ID:-}" ] && [ "$VERIFICATION_REQUEST_ID" != "null" ]; then
      docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -q \
        -c "DELETE FROM seller_verifications WHERE id = '$VERIFICATION_REQUEST_ID';" 2>/dev/null
      echo -e "  ${DIM}Cleaned up test verification${NC}"
    fi
    echo -e "  ${GREEN}Cleanup complete${NC}"
  else
    echo -e "  ${YELLOW}Docker not available — manual cleanup may be needed${NC}"
  fi
fi

# ── Final Summary ─────────────────────────────────────────────────

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║               SUITE RESULTS                       ║${NC}"
echo -e "${BOLD}╠═══════════════════════════════════════════════════╣${NC}"

for result in "${SUITE_RESULTS[@]}"; do
  echo -e "  $result"
done

echo -e "${BOLD}╚═══════════════════════════════════════════════════╝${NC}"

if [ ${#FAILED_SUITES[@]} -gt 0 ]; then
  echo ""
  echo -e "${RED}${BOLD}${#FAILED_SUITES[@]} suite(s) had failures:${NC}"
  for fs in "${FAILED_SUITES[@]}"; do
    echo -e "  ${RED}• $fs${NC}"
  done
  echo ""
  echo -e "${DIM}Re-run a single suite: ./run-all.sh $fs${NC}"
  exit 1
else
  echo ""
  echo -e "${GREEN}${BOLD}All suites passed!${NC}"
  exit 0
fi
